# Generated by Django 2.2.3 on 2020-04-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
