# Generated by Django 2.2.3 on 2020-04-28 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20200429_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
