# Generated by Django 2.2.3 on 2019-07-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': (('manage_category', 'Manage blog categories.'),)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('manage_post', 'Manage blog posts.'),)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'permissions': (('manage_tag', 'Manage blog tags.'),)},
        ),
    ]
