# Generated by Django 2.2.3 on 2019-07-10 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='Keywords')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='sites.Site')),
            ],
        ),
    ]
