# Generated by Django 2.2.3 on 2019-07-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0004_socialnetwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialnetwork',
            name='site_settings',
        ),
    ]
