# Generated by Django 2.2.3 on 2019-07-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0005_remove_socialnetwork_site_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='icon',
            field=models.CharField(blank=True, max_length=100, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='link',
            field=models.CharField(max_length=255, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
