# Generated by Django 2.2.3 on 2020-04-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Is Featured'),
        ),
    ]
