# Generated by Django 2.2.3 on 2019-07-10 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('manage_customer', 'Manage customers.'), ('manage_staff', 'Manage staffs.'))},
        ),
    ]
